export const FETCH_POST = "FETCH_POST"
export const UPDATE_LIKES_POST = "UPDATE_LIKES_POST"
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS"
export const SEND_POST = "UPDARE_USER_DETAILS"

//Post creation actions types
export const CREATE_POST_BUILD = "CREATE_POST_BUILD"
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS = "CREATE_POST_SENDING"
export const CREATE_POST_FAIL = "CREATE_POST_FAIL"

export const GET_POST_REQUEST = "GET_POST_REQUEST"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_ERROR = "GET_POST_ERROR"

export const RE_GET_POST_REQUEST = "RE_GET_POST_REQUEST"
export const RE_GET_POST_SUCCESS = "RE_GET_POST_SUCCESS"
export const RE_GET_POST_ERROR = "RE_GET_POST_ERROR"
